vich_uploader:
    db_driver: orm # Utilisez 'orm' pour Doctrine ORM, 'mongodb' pour MongoDB ODM
    mappings:
        Produits:
            uri_prefix: '/images'
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
