controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_acceuil:
    path: '/'
    controller: App\Controller\AcceuilController::index

app_les_produits:
    path: '/lesProduits'
    controller: App\Controller\LesProduitsController::index

app_actualite:
    path: '/actualite'
    controller: App\Controller\ActualitéController::index

app_application:
    path: '/application'
    controller: App\Controller\ApplicationController::index

app_catalogue:
    path: '/catalogue'
    controller: App\Controller\CatalogueController::index

app_partenaire:
    path: '/partenaire'
    controller: App\Controller\PartenaireController::index
